### ISSUE TITLE
Misplacement of dialogue box in dual monitor setup

### ISSUE THREAD

**Issue by Palisand** [davkean/audio-switcher#35]
Instead of appearing directly on top of the taskbar, audio-switcher's dialogue box appears on the second monitor, to the right of the taskbar.

**Comment by davkean** [comment]
Yeah, I've seen this before. I plan on rewriting the notification icon support, and as part of that, will get better information on where the notify icon is (currently I have zero information on that). I'll fix the placement when in do that.

**Comment by Palisand** [comment]
Cool

**Comment by davkean** [comment]
Duplicate of https://github.com/davkean/audio-switcher/issues/15.
