### ISSUE TITLE
Looks like the IPolicyConfig3 Guid changed again

### ISSUE THREAD

**Issue by Ventajou** [davkean/audio-switcher#36]
I'm using Win 10 build 10525 and getting crashes when I try switching device. [Same spot as before](https://github.com/davkean/audio-switcher/blob/master/src/AudioSwitcher/Audio/AudioDeviceManager.cs#L95), could you please let me know what the new Guid is or better, tell me how to find out myself? It seems insider builds frequently break this.

**Comment by davkean** [comment]
Yeah, I should change this code to use dynamic instead, switch from using the cast to `dynamic config = new PolicyConfig();'

**Comment by Ventajou** [comment]
that didn't help...

Unable to cast COM object of type 'AudioSwitcher.Audio.Interop.PolicyConfig' to interface type 'AudioSwitcher.Audio.Interop.IPolicyConfig3'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{CA286FC3-91FD-42C3-8E9B-CAAFA66242E3}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).

**Comment by davkean** [comment]
Sorry, I meant, remove the cast completely, and call SetDefaultEndpoint on dynamic. If it implements IDispatch that should theoretically work. If not, use the GUID of IUnknown on IPolicyConfig3 and try that.

**Comment by Ventajou** [comment]
The IUnknown Guid did the trick, thanks!

**Comment by irzyxa** [comment]
New GUID 6be54be8-a068-4875-a49d-0c2966473b11
